package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.plaf.basic.BasicDirectoryModel;
import misc.Assets;
import misc.MiscMath;
import world.World;
import world.terrain.Generator;

public final class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private GUI() {
        initComponents();
    }
    
    private static GUI gui;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigator = new javax.swing.JDialog();
        mapView = new gui.MiniMap();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        noiseMapOptions = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        noiseMapElevationSlider = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        noiseMapAlgoChooser = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        noOptionsPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        scatterOptions = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        scatterAmountSlider = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        scatterMinSlider = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        scatterMaxSlider = new javax.swing.JSlider();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        canvas = new gui.Canvas();
        layerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        layerList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        layerUpButton = new javax.swing.JButton();
        layerDownButton = new javax.swing.JButton();
        editLayerButton = new javax.swing.JButton();
        regenLayerButton = new javax.swing.JButton();
        addLayerButton = new javax.swing.JButton();
        deleteLayerButton = new javax.swing.JButton();
        editLayerPanel = new javax.swing.JPanel();
        applyLayerChangesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        layerNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editLayerTitleLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        layerTileChooser = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tileRestrictionList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        restrictionModeChooser = new javax.swing.JComboBox<>();
        cancelLayerChangesButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        layerElevationSpinner = new javax.swing.JSpinner();
        generatorTitlePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        generatorChooser = new javax.swing.JComboBox<>();
        openCommandLineButton = new javax.swing.JButton();
        seedField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        randomSeedButton = new javax.swing.JButton();
        generatorBottomPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        genOptionsScrollPane = new javax.swing.JScrollPane();
        generatorBodyPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newWorldButton = new javax.swing.JMenuItem();
        openWorldButton = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exportTerrainButton = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        exitButton = new javax.swing.JMenuItem();
        worldMenu = new javax.swing.JMenu();
        showNavigatorButton = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        chooseSpriteSheetMenu = new javax.swing.JMenu();
        earthSpritesheetButton = new javax.swing.JMenuItem();
        marsSpritesheetButton = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        customSpritesheetButton = new javax.swing.JMenuItem();
        setSeedButton = new javax.swing.JMenuItem();

        navigator.setTitle("Navigator");
        navigator.setAlwaysOnTop(true);
        navigator.setBounds(new java.awt.Rectangle(100, 100, 500, 500));
        navigator.setIconImage(getIconImage());
        navigator.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                navigatorFocusLost(evt);
            }
        });

        mapView.setBackground(new java.awt.Color(0, 0, 0));
        mapView.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mapViewFocusLost(evt);
            }
        });

        javax.swing.GroupLayout mapViewLayout = new javax.swing.GroupLayout(mapView);
        mapView.setLayout(mapViewLayout);
        mapViewLayout.setHorizontalGroup(
            mapViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        mapViewLayout.setVerticalGroup(
            mapViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navigatorLayout = new javax.swing.GroupLayout(navigator.getContentPane());
        navigator.getContentPane().setLayout(navigatorLayout);
        navigatorLayout.setHorizontalGroup(
            navigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navigatorLayout.setVerticalGroup(
            navigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("Create natural, flowing terrain shapes.");

        jLabel11.setText("Elevation");

        jLabel12.setText("0%");

        noiseMapElevationSlider.setPaintLabels(true);
        noiseMapElevationSlider.setValue(0);
        noiseMapElevationSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                noiseMapElevationSliderStateChanged(evt);
            }
        });

        jLabel13.setText("100%");

        noiseMapAlgoChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perlin", "Diamond Square" }));
        noiseMapAlgoChooser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noiseMapAlgoChooserItemStateChanged(evt);
            }
        });

        jLabel7.setText("Style");

        javax.swing.GroupLayout noiseMapOptionsLayout = new javax.swing.GroupLayout(noiseMapOptions);
        noiseMapOptions.setLayout(noiseMapOptionsLayout);
        noiseMapOptionsLayout.setHorizontalGroup(
            noiseMapOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(noiseMapOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                        .addGroup(noiseMapOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noiseMapElevationSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(noiseMapAlgoChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noiseMapOptionsLayout.setVerticalGroup(
            noiseMapOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noiseMapOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(noiseMapOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noiseMapElevationSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noiseMapAlgoChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        noOptionsPanel.setAutoscrolls(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setText("No options available.");

        javax.swing.GroupLayout noOptionsPanelLayout = new javax.swing.GroupLayout(noOptionsPanel);
        noOptionsPanel.setLayout(noOptionsPanelLayout);
        noOptionsPanelLayout.setHorizontalGroup(
            noOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        noOptionsPanelLayout.setVerticalGroup(
            noOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scatterOptions.setAutoscrolls(true);

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("Create scattered plots of tiles.");

        scatterAmountSlider.setPaintLabels(true);
        noiseMapElevationSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                Generator.getGenerator("NoiseMap").setParameter("cutoff", ""+((double)noiseMapElevationSlider.getValue()/100d));
            }
        });
        scatterAmountSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scatterAmountSliderStateChanged(evt);
            }
        });

        jLabel16.setText("Cover amount");

        jLabel17.setText("0%");

        jLabel18.setText("100%");

        scatterMinSlider.setPaintLabels(true);
        scatterMinSlider.setValue(0);
        noiseMapElevationSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                Generator.getGenerator("NoiseMap").setParameter("cutoff", ""+((double)noiseMapElevationSlider.getValue()/100d));
            }
        });
        scatterMinSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scatterMinSliderStateChanged(evt);
            }
        });

        jLabel19.setText("Minimum probability");

        jLabel20.setText("0%");

        jLabel21.setText("100%");

        jLabel22.setText("0%");

        scatterMaxSlider.setPaintLabels(true);
        scatterMaxSlider.setValue(100);
        noiseMapElevationSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                Generator.getGenerator("NoiseMap").setParameter("cutoff", ""+((double)noiseMapElevationSlider.getValue()/100d));
            }
        });
        scatterMaxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scatterMaxSliderStateChanged(evt);
            }
        });

        jLabel23.setText("100%");

        jLabel24.setText("Maximum probability");

        javax.swing.GroupLayout scatterOptionsLayout = new javax.swing.GroupLayout(scatterOptions);
        scatterOptions.setLayout(scatterOptionsLayout);
        scatterOptionsLayout.setHorizontalGroup(
            scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scatterOptionsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scatterOptionsLayout.createSequentialGroup()
                        .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scatterOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(scatterOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scatterAmountSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(scatterOptionsLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scatterOptionsLayout.createSequentialGroup()
                        .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scatterOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(scatterOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scatterMinSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(scatterOptionsLayout.createSequentialGroup()
                        .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scatterOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(scatterOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scatterMaxSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)))
                .addGap(20, 20, 20))
        );
        scatterOptionsLayout.setVerticalGroup(
            scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scatterOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scatterAmountSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scatterMinSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scatterOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scatterMaxSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Advanced Terrain Generation Tool - Untitled World");
        setBounds(new java.awt.Rectangle(100, 100, 550, 900));
        setIconImages(getIconImages());

        canvas.setBackground(new java.awt.Color(0, 0, 0));
        canvas.setDoubleBuffered(false);
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
        });

        layerPanel.setPreferredSize(new java.awt.Dimension(292, 242));

        layerList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        layerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Untitled Layer" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        layerList.setSelectedIndices(new int[] {0});
        layerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                layerListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(layerList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Layers");

        layerUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/up.png"))); // NOI18N
        layerUpButton.setToolTipText("Move up");
        layerUpButton.setEnabled(false);
        layerUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layerUpButtonActionPerformed(evt);
            }
        });

        layerDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down.png"))); // NOI18N
        layerDownButton.setToolTipText("Move down");
        layerDownButton.setEnabled(false);
        layerDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layerDownButtonActionPerformed(evt);
            }
        });

        editLayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editLayerButton.setToolTipText("Edit layer properties");
        editLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLayerButtonActionPerformed(evt);
            }
        });

        regenLayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/favicon-16.png"))); // NOI18N
        regenLayerButton.setToolTipText("Terrain generation");
        regenLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regenLayerButtonActionPerformed(evt);
            }
        });

        addLayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addLayerButton.setToolTipText("Add layer");
        addLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLayerButtonActionPerformed(evt);
            }
        });

        deleteLayerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        deleteLayerButton.setToolTipText("Delete layer");
        deleteLayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layerPanelLayout = new javax.swing.GroupLayout(layerPanel);
        layerPanel.setLayout(layerPanelLayout);
        layerPanelLayout.setHorizontalGroup(
            layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regenLayerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editLayerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addLayerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layerDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layerUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteLayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layerPanelLayout.setVerticalGroup(
            layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerPanelLayout.createSequentialGroup()
                        .addComponent(addLayerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editLayerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(layerUpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(layerDownButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteLayerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regenLayerButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        editLayerPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                editLayerPanelPropertyChange(evt);
            }
        });

        applyLayerChangesButton.setText("Apply changes");
        applyLayerChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLayerChangesButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Tile");

        editLayerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editLayerTitleLabel.setText("Editing layer properties");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/left.png"))); // NOI18N

        layerTileChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<no tiles defined>" }));

        tileRestrictionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<no tiles defined>" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tileRestrictionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tileRestrictionListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(tileRestrictionList);

        jLabel4.setText("Tile placement restrictions");

        restrictionModeChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allow all", "Allow selected", "Block selected" }));

        cancelLayerChangesButton.setText("Cancel");
        cancelLayerChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLayerChangesButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Elevation");

        layerElevationSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                layerElevationSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout editLayerPanelLayout = new javax.swing.GroupLayout(editLayerPanel);
        editLayerPanel.setLayout(editLayerPanelLayout);
        editLayerPanelLayout.setHorizontalGroup(
            editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(layerNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(layerTileChooser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(editLayerTitleLabel)
                    .addComponent(applyLayerChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelLayerChangesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(layerElevationSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(restrictionModeChooser, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        editLayerPanelLayout.setVerticalGroup(
            editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(editLayerTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restrictionModeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editLayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(layerElevationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(layerTileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(applyLayerChangesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelLayerChangesButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Generate terrain");

        generatorChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<no generators found>" }));
        generatorChooser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                generatorChooserItemStateChanged(evt);
            }
        });
        generatorChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                generatorChooserMouseReleased(evt);
            }
        });
        generatorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatorChooserActionPerformed(evt);
            }
        });

        openCommandLineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/terminal.png"))); // NOI18N
        openCommandLineButton.setToolTipText("Advanced options...");
        openCommandLineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCommandLineButtonActionPerformed(evt);
            }
        });

        seedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seedFieldKeyReleased(evt);
            }
        });

        jLabel9.setText("Seed:");

        randomSeedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        randomSeedButton.setToolTipText("Advanced options...");
        randomSeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomSeedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generatorTitlePanelLayout = new javax.swing.GroupLayout(generatorTitlePanel);
        generatorTitlePanel.setLayout(generatorTitlePanelLayout);
        generatorTitlePanelLayout.setHorizontalGroup(
            generatorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatorTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generatorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generatorTitlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seedField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomSeedButton))
                    .addGroup(generatorTitlePanelLayout.createSequentialGroup()
                        .addGroup(generatorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(generatorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openCommandLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        generatorTitlePanelLayout.setVerticalGroup(
            generatorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generatorTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generatorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(generatorTitlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generatorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(openCommandLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generatorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(randomSeedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seedField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Generate!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generatorBottomPanelLayout = new javax.swing.GroupLayout(generatorBottomPanel);
        generatorBottomPanel.setLayout(generatorBottomPanelLayout);
        generatorBottomPanelLayout.setHorizontalGroup(
            generatorBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatorBottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        generatorBottomPanelLayout.setVerticalGroup(
            generatorBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generatorBottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(generatorBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        genOptionsScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        genOptionsScrollPane.setBorder(null);
        genOptionsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout generatorBodyPanelLayout = new javax.swing.GroupLayout(generatorBodyPanel);
        generatorBodyPanel.setLayout(generatorBodyPanelLayout);
        generatorBodyPanelLayout.setHorizontalGroup(
            generatorBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        generatorBodyPanelLayout.setVerticalGroup(
            generatorBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        genOptionsScrollPane.setViewportView(generatorBodyPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(genOptionsScrollPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(genOptionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canvasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(generatorBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generatorTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(editLayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, canvasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generatorTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(generatorBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(layerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(editLayerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        newWorldButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newWorldButton.setText("New world");
        newWorldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWorld(evt);
            }
        });
        fileMenu.add(newWorldButton);

        openWorldButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openWorldButton.setText("Open world...");
        openWorldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openWorldButtonActionPerformed(evt);
            }
        });
        fileMenu.add(openWorldButton);

        jMenuItem3.setText("Save world...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem3);
        fileMenu.add(jSeparator3);

        exportTerrainButton.setText("Export terrain...");
        exportTerrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTerrainButtonActionPerformed(evt);
            }
        });
        fileMenu.add(exportTerrainButton);
        fileMenu.add(jSeparator4);

        exitButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        fileMenu.add(exitButton);

        menuBar.add(fileMenu);

        worldMenu.setText("World");

        showNavigatorButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        showNavigatorButton.setText("Navigator...");
        showNavigatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNavigatorButtonActionPerformed(evt);
            }
        });
        worldMenu.add(showNavigatorButton);
        worldMenu.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Resize world...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        worldMenu.add(jMenuItem4);

        chooseSpriteSheetMenu.setText("Choose tile spritesheet...");

        earthSpritesheetButton.setText("Earth");
        earthSpritesheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earthSpritesheetButtonActionPerformed(evt);
            }
        });
        chooseSpriteSheetMenu.add(earthSpritesheetButton);

        marsSpritesheetButton.setText("Mars");
        marsSpritesheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsSpritesheetButtonActionPerformed(evt);
            }
        });
        chooseSpriteSheetMenu.add(marsSpritesheetButton);
        chooseSpriteSheetMenu.add(jSeparator2);

        customSpritesheetButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        customSpritesheetButton.setText("Pick a file...");
        customSpritesheetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customSpritesheetButtonActionPerformed(evt);
            }
        });
        chooseSpriteSheetMenu.add(customSpritesheetButton);

        worldMenu.add(chooseSpriteSheetMenu);

        setSeedButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        setSeedButton.setText("Set seed...");
        setSeedButton.setEnabled(false);
        setSeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSeedButtonActionPerformed(evt);
            }
        });
        worldMenu.add(setSeedButton);

        menuBar.add(worldMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newWorld(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWorld
        World.newWorld(64, 64);
        refreshLayerList();
        editLayerPanel.setVisible(false);
        canvas.repaint();
    }//GEN-LAST:event_newWorld

    @Override
    public Image getIconImage() {
        return getIconImage(32);
    }

    @Override
    public List<Image> getIconImages() {
        ArrayList<Image> icons = new ArrayList<Image>();
        icons.add(getIconImage(16));
        icons.add(getIconImage(32));
        icons.add(getIconImage(48));
        icons.add(getIconImage(64));
        return icons;
    }

    public Image getIconImage(int size) {
        try {
            InputStream img = GUI.class.getResourceAsStream("/resources/favicon-"+size+".png");
            if (img == null) return null;
            return ImageIO.read(img);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void customSpritesheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customSpritesheetButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int success = chooser.showOpenDialog(gui);
        if (success == JFileChooser.APPROVE_OPTION) {
            File chosen = chooser.getSelectedFile();
            try {
                World.getWorld().setSpritesheet(chosen.getAbsolutePath());
                System.out.println("Set world spritesheet file to "+chosen.getAbsolutePath());
                String tdefs = JOptionPane.showInputDialog(gui, 
                        "Type the name of each tile in order, comma separated:", 
                        "Add tile definitions", JOptionPane.QUESTION_MESSAGE);
                String tdefspl[] = tdefs.split("\\s*,\\s*");
                World.getWorld().setTileNames(tdefspl);
                editLayerPanel.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(gui, "You need to choose a valid image file! (.png, .jpg, etc...)", 
                        "Invalid spritesheet", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_customSpritesheetButtonActionPerformed

    private void setSeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSeedButtonActionPerformed
        World.getWorld().setSeed(Long.parseLong(JOptionPane.showInputDialog(gui, "Seed (integer):")));
    }//GEN-LAST:event_setSeedButtonActionPerformed

    private void showNavigatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNavigatorButtonActionPerformed
        showDialog(navigator, false);
    }//GEN-LAST:event_showNavigatorButtonActionPerformed

    private void navigatorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_navigatorFocusLost
        navigator.setVisible(false);
    }//GEN-LAST:event_navigatorFocusLost

    private void mapViewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mapViewFocusLost
        navigator.setVisible(false);
    }//GEN-LAST:event_mapViewFocusLost

    private void earthSpritesheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earthSpritesheetButtonActionPerformed
        World.getWorld().setSpritesheet("resources/samples/terrain/earth.png");
        World.getWorld().setTileNames(new String[]{"Stone", "Lava", "Sand", "Dirt", "Grass", "Snow", "Ice", "Water", "Tree", "Rocks", "Chest"});
        editLayerPanel.setVisible(false);
    }//GEN-LAST:event_earthSpritesheetButtonActionPerformed

    private void marsSpritesheetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsSpritesheetButtonActionPerformed
        World.getWorld().setSpritesheet("resources/samples/terrain/mars.png");
        World.getWorld().setTileNames(new String[]{"Sand", "Ice", "Rocks"});
        editLayerPanel.setVisible(false);
    }//GEN-LAST:event_marsSpritesheetButtonActionPerformed

    private void exportTerrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTerrainButtonActionPerformed
        JFileChooser saver = new JFileChooser();
        saver.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int success = saver.showSaveDialog(gui);
        if (success == JFileChooser.APPROVE_OPTION) {
            boolean saved = World.getWorld().exportTerrain(saver.getSelectedFile());
            JOptionPane.showMessageDialog(gui, 
                    saved ? "Terrain data has been exported!" : "Error exporting terrain data!", 
                    saved ? "Success" : "Error",
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon(gui.getIconImage(32)));
        }
    }//GEN-LAST:event_exportTerrainButtonActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String input = JOptionPane.showInputDialog(gui, 
                        "Enter the new world size (i.e. \"64, 64\")", 
                        "Resize world", JOptionPane.QUESTION_MESSAGE);
        String[] dims = input.split("\\s*,\\s*");
        World.getWorld().resize(Integer.parseInt(dims[0]), Integer.parseInt(dims[1]));
        canvas.repaint();
        refreshLayerList();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser saver = new JFileChooser();
        saver.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int success = saver.showSaveDialog(gui);
        if (success == JFileChooser.APPROVE_OPTION) {
            boolean saved = World.getWorld().save(saver.getSelectedFile());
            JOptionPane.showMessageDialog(gui, 
                    saved ? "World has been saved!" : "Error saving world!", 
                    saved ? "Success" : "Error",
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon(gui.getIconImage(32)));
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void openWorldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openWorldButtonActionPerformed
        JFileChooser saver = new JFileChooser();
        saver.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int success = saver.showSaveDialog(gui);
        if (success == JFileChooser.APPROVE_OPTION) {
            World.newWorld(0, 0);
            boolean saved = World.getWorld().load(saver.getSelectedFile());
            JOptionPane.showMessageDialog(gui, 
                    saved ? "World has been loaded!" : "Error loading world!", 
                    saved ? "Success" : "Error",
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon(gui.getIconImage(32)));
        }
        refreshLayerList();
        editLayerPanel.setVisible(false);
        canvas.repaint();
    }//GEN-LAST:event_openWorldButtonActionPerformed

    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        canvas.repaint();
    }//GEN-LAST:event_canvasMouseClicked

    private void editLayerPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_editLayerPanelPropertyChange
        System.out.println(evt.getPropertyName());
    }//GEN-LAST:event_editLayerPanelPropertyChange

    private void cancelLayerChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLayerChangesButtonActionPerformed
        editLayerPanel.setVisible(false);
    }//GEN-LAST:event_cancelLayerChangesButtonActionPerformed

    private void tileRestrictionListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tileRestrictionListValueChanged

    }//GEN-LAST:event_tileRestrictionListValueChanged

    private void applyLayerChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLayerChangesButtonActionPerformed
        boolean comma = layerNameField.getText().contains(",");
        if (layerNameField.getText().trim().length() == 0 || comma) {
            JOptionPane.showMessageDialog(gui,
                !comma ? "You cannot have a blank layer name!" : "Commas are not allowed in layer names!",
                "Invalid name", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //apply layer properties
        int[] layers = layerList.getSelectedIndices();
        for (int layer: layers) {
            World.getWorld().setLayerProperty("name", layerNameField.getText(), layer);
            World.getWorld().setLayerProperty("tile", layerTileChooser.getSelectedIndex(), layer);
            World.getWorld().setLayerProperty("rmode", restrictionModeChooser.getSelectedIndex(), layer);
            World.getWorld().setLayerProperty("rtiles", tileRestrictionList.getSelectedIndices(), layer);
            World.getWorld().setLayerProperty("elevation", layerElevationSpinner.getValue(), layerList.getSelectedIndex());
        }
        canvas.repaint();
        refreshLayerList();
        editLayerPanel.setVisible(false);
    }//GEN-LAST:event_applyLayerChangesButtonActionPerformed

    private void addLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLayerButtonActionPerformed
        World.getWorld().newLayer();
        gui.refreshLayerList();
        layerList.setSelectedIndex(0);
        canvas.repaint();
        layerList.ensureIndexIsVisible(layerList.getSelectedIndex());
    }//GEN-LAST:event_addLayerButtonActionPerformed

    private void regenLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regenLayerButtonActionPerformed
        int gindex = generatorChooser.getSelectedIndex();
        DefaultComboBoxModel<String> m = new DefaultComboBoxModel<String>();
        for (int i = 0; i < Generator.generatorCount(); i++)
            m.addElement(Generator.getGeneratorName(i));
        generatorChooser.setModel(m);
        generatorChooser.setSelectedIndex(-1);
        generatorChooser.setSelectedIndex(gindex);
        //repaint
        canvas.repaint();
        setGeneratorPanelVisible(true);
    }//GEN-LAST:event_regenLayerButtonActionPerformed

    private void deleteLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLayerButtonActionPerformed
        //deleye layers
        int[] layers = layerList.getSelectedIndices();
        int start_index = layerList.getSelectedIndex();
        for (int l = layers.length - 1; l > -1; l--) {
            //System.out.println("Removing layer: "+layers[l]);
            World.getWorld().removeLayer(layers[l]);
        }
        if (World.getWorld().layerCount() == 0) World.getWorld().newLayer();
        layerList.setSelectedIndex((int)MiscMath.clamp(start_index, 0, World.getWorld().layerCount() - 1));
        refreshLayerList();
        editLayerPanel.setVisible(false);
        canvas.repaint();
    }//GEN-LAST:event_deleteLayerButtonActionPerformed

    private void editLayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLayerButtonActionPerformed
        refreshLayerList();
        canvas.repaint();
        editLayerPanel.setVisible(true);
    }//GEN-LAST:event_editLayerButtonActionPerformed

    private void layerDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layerDownButtonActionPerformed
        World.getWorld().reorderLayer(layerList.getSelectedIndex(), 1);
        canvas.repaint();
        refreshLayerList();
    }//GEN-LAST:event_layerDownButtonActionPerformed

    private void layerUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layerUpButtonActionPerformed
        World.getWorld().reorderLayer(layerList.getSelectedIndex(), -1);
        canvas.repaint();
        refreshLayerList();
    }//GEN-LAST:event_layerUpButtonActionPerformed

    private void layerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_layerListValueChanged
        if (evt.getFirstIndex() == -1) layerList.setSelectedIndex(0);
        int scount = evt.getLastIndex() - evt.getFirstIndex();
        editLayerPanel.setVisible(false);
    }//GEN-LAST:event_layerListValueChanged

    private void generatorChooserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generatorChooserMouseReleased

    }//GEN-LAST:event_generatorChooserMouseReleased

    private void generatorChooserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_generatorChooserItemStateChanged

        if (generatorChooser.getSelectedIndex() == -1) return;
        Generator g = Generator.getGenerator(generatorChooser.getSelectedIndex());
        
        JPanel[] panels = new JPanel[] {
            noOptionsPanel, 
            noOptionsPanel,
            noiseMapOptions,
            scatterOptions
        };
        
        generatorBodyPanel.removeAll();
        generatorBodyPanel.setLayout(new BorderLayout());
        generatorBodyPanel.add(panels[generatorChooser.getSelectedIndex()], BorderLayout.CENTER);
        generatorBodyPanel.revalidate();
        generatorBodyPanel.repaint();
        
        seedField.setText(g.getSeed()+"");
        seedField.setForeground(Color.black);
        
    }//GEN-LAST:event_generatorChooserItemStateChanged

    private void openCommandLineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCommandLineButtonActionPerformed
        String s = JOptionPane.showInputDialog(gui, "Parameters:", 
                World.getWorld().getLayerProperty("lastcmd", Canvas.layer()));
        if (s == null) return; s = s.trim();
        World.getWorld().setLayerProperty("lastcmd", s, Canvas.layer());
        //split by colon
        String split[] = s.split("\\s*:\\s*");
        if (split.length == 0) { System.err.println("Invalid input!"); return; }
        //find generator type
        String gname = split[0].trim(); 
        Generator g = Generator.getGenerator(gname);
        
        if (split.length > 1) { //if params actually exist
            String params = split[1].trim();
            System.out.println(gname);
            //find parameters
            String[] params_spl = params.split("\\s*,\\s*");
            if (g == null) { System.err.println("Generator '"+gname+"' not found!"); return; }
            for (int i = 0; i < params_spl.length; i++) {
                String spl[] = params_spl[i].split("\\s*=\\s*");
                String name = spl[0]; String val = spl[1];
                g.setParameter(name, val);
                System.out.println(gname+" parameter: "+name+" = "+val);
            }
        }
        
        //clear and generate
        
        int[] selected = layerList.getSelectedIndices();
        for (int l = selected.length - 1; l > -1; l--) {
            World.getWorld().clearTiles(selected[l]);
            g.generate(World.getWorld(), selected[l]);
        }
        //repaint
        canvas.repaint();
    }//GEN-LAST:event_openCommandLineButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setGeneratorPanelVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Generator g = Generator.getGenerator(generatorChooser.getSelectedIndex());
        g.reset();
        int[] selected = layerList.getSelectedIndices();
        for (int l = selected.length - 1; l > -1; l--) {
            World.getWorld().clearTiles(selected[l]);
            g.generate(World.getWorld(), selected[l]);
        }
        canvas.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void noiseMapElevationSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_noiseMapElevationSliderStateChanged
        Generator.getGenerator("NoiseMap").setParameter("elevation", ""+((double)noiseMapElevationSlider.getValue()/100d));
    }//GEN-LAST:event_noiseMapElevationSliderStateChanged

    private void scatterAmountSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scatterAmountSliderStateChanged
        Generator.getGenerator("Scattered").setParameter("amount", ""+((double)scatterAmountSlider.getValue()/100d));
    }//GEN-LAST:event_scatterAmountSliderStateChanged

    private void scatterMinSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scatterMinSliderStateChanged
        Generator.getGenerator("Scattered").setParameter("min", ""+((double)scatterMinSlider.getValue()/100d));
    }//GEN-LAST:event_scatterMinSliderStateChanged

    private void scatterMaxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scatterMaxSliderStateChanged
       Generator.getGenerator("Scattered").setParameter("max", ""+((double)scatterMaxSlider.getValue()/100d));
    }//GEN-LAST:event_scatterMaxSliderStateChanged

    private void noiseMapAlgoChooserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noiseMapAlgoChooserItemStateChanged
        String[] algos = new String[]{"Perlin", "DiamondSquare"};
        Generator.getGenerator("NoiseMap").setParameter("algo", algos[noiseMapAlgoChooser.getSelectedIndex()]);
    }//GEN-LAST:event_noiseMapAlgoChooserItemStateChanged

    private void layerElevationSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_layerElevationSpinnerStateChanged
        canvas.repaint();
    }//GEN-LAST:event_layerElevationSpinnerStateChanged

    private void randomSeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomSeedButtonActionPerformed
        seedField.setText(new Random().nextInt()+"");
        Generator g = Generator.getGenerator(generatorChooser.getSelectedIndex());
        g.setSeed(Long.parseLong(seedField.getText()));
        seedField.setForeground(Color.black);
        
    }//GEN-LAST:event_randomSeedButtonActionPerformed

    private void seedFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seedFieldKeyReleased
        boolean valid = seedField.getText().matches("(-)*\\d+")
                && seedField.getText().length() < 16;
        Generator g = Generator.getGenerator(generatorChooser.getSelectedIndex());
        if (valid) g.setSeed(Long.parseLong(seedField.getText()));
        seedField.setForeground(valid ? Color.black : Color.red);
    }//GEN-LAST:event_seedFieldKeyReleased

    private void generatorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatorChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generatorChooserActionPerformed

    /**
     * Show (and make modal) a custom dialog popup.
     * @param d The JDialog to show.
     * @param modal Modal, or not?
     */
    public static void showDialog(JDialog d, boolean modal) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        d.setLocation(gui.getX() + (int) (gui.getWidth() / 2) - (d.getWidth() / 2),
                gui.getY() + (int) (gui.getHeight() / 2) - ((d.getHeight() / 2)));
        d.setModal(modal);
        d.setModalityType(modal ? Dialog.ModalityType.APPLICATION_MODAL : Dialog.ModalityType.MODELESS);
        d.setVisible(true);
        System.out.println("Showing " + d.getTitle());
    }
    
    private void setGeneratorPanelVisible(boolean v) {
        generatorTitlePanel.setVisible(v);
        generatorBodyPanel.setVisible(v);
        generatorBottomPanel.setVisible(v);
        genOptionsScrollPane.setVisible(v);
        jPanel1.setVisible(v);
    }
    
    /**
     * Refresh input fields and the list of layers in the corner of the Canvas.
     */
    public void refreshLayerList() {
        DefaultListModel m = new DefaultListModel();
        int[] indices = layerList.getSelectedIndices();
        for (int i = 0; i < World.getWorld().layerCount(); i++) 
            m.addElement(World.getWorld().getLayerProperty("name", i));
        layerList.setModel(m);
        layerList.setSelectedIndices(indices);
        
        boolean multiple = layerList.getSelectedIndices().length > 1;
        
        //update layer edit panel
        layerNameField.setText(multiple ? "" : (String)World.getWorld().getLayerProperty("name", layerList.getSelectedIndex()));
        DefaultComboBoxModel<String> md = new DefaultComboBoxModel<String>();
        DefaultListModel dlm = new DefaultListModel();
        for (String tile: World.getWorld().getTileNames()) { md.addElement(tile); dlm.addElement(tile); }
        layerTileChooser.setModel(md);
        tileRestrictionList.setModel(dlm);
        layerTileChooser.setSelectedIndex(multiple ? 0 
                : (Integer)World.getWorld().getLayerProperty("tile", layerList.getSelectedIndex()));
        restrictionModeChooser.setSelectedIndex(multiple ? 0 
                : (Integer)World.getWorld().getLayerProperty("rmode", layerList.getSelectedIndex()));
        tileRestrictionList.setSelectedIndices(multiple ? new int[]{} 
                : (int[])World.getWorld().getLayerProperty("rtiles", layerList.getSelectedIndex()));
        
        editLayerTitleLabel.setText(multiple ? "Editing multiple layers" : "Editing layer properties");
        layerElevationSpinner.setValue(multiple ? 0 : World.getWorld().getLayerProperty("elevation", layerList.getSelectedIndex()));
        
        //layerUpButton.setEnabled(layerList.getSelectedIndex() > 0);
        //layerDownButton.setEnabled(layerList.getSelectedIndex() < m.getSize() - 1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Assets.init();
                gui = new GUI();
                gui.setVisible(true);
                World.newWorld(64, 64);
                gui.refreshLayerList();
                gui.setGeneratorPanelVisible(false);
            }
        });
    }
    
    protected static Canvas getCanvas() { return gui == null ? null : gui.canvas; }
    protected static MiniMap getMiniMap() { return gui == null ? null : gui.mapView; }
    protected static JList getLayerList() { return layerList; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLayerButton;
    private javax.swing.JButton applyLayerChangesButton;
    private javax.swing.JButton cancelLayerChangesButton;
    private gui.Canvas canvas;
    private javax.swing.JMenu chooseSpriteSheetMenu;
    private javax.swing.JMenuItem customSpritesheetButton;
    private javax.swing.JButton deleteLayerButton;
    private javax.swing.JMenuItem earthSpritesheetButton;
    private javax.swing.JButton editLayerButton;
    private javax.swing.JPanel editLayerPanel;
    private javax.swing.JLabel editLayerTitleLabel;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JMenuItem exportTerrainButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane genOptionsScrollPane;
    private javax.swing.JPanel generatorBodyPanel;
    private javax.swing.JPanel generatorBottomPanel;
    private javax.swing.JComboBox<String> generatorChooser;
    private javax.swing.JPanel generatorTitlePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JButton layerDownButton;
    private javax.swing.JSpinner layerElevationSpinner;
    private static javax.swing.JList<String> layerList;
    private javax.swing.JTextField layerNameField;
    private javax.swing.JPanel layerPanel;
    private javax.swing.JComboBox<String> layerTileChooser;
    private javax.swing.JButton layerUpButton;
    private gui.MiniMap mapView;
    private javax.swing.JMenuItem marsSpritesheetButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JDialog navigator;
    private javax.swing.JMenuItem newWorldButton;
    private javax.swing.JPanel noOptionsPanel;
    private javax.swing.JComboBox<String> noiseMapAlgoChooser;
    private javax.swing.JSlider noiseMapElevationSlider;
    private javax.swing.JPanel noiseMapOptions;
    private javax.swing.JButton openCommandLineButton;
    private javax.swing.JMenuItem openWorldButton;
    private javax.swing.JButton randomSeedButton;
    private javax.swing.JButton regenLayerButton;
    private javax.swing.JComboBox<String> restrictionModeChooser;
    private javax.swing.JSlider scatterAmountSlider;
    private javax.swing.JSlider scatterMaxSlider;
    private javax.swing.JSlider scatterMinSlider;
    private javax.swing.JPanel scatterOptions;
    private javax.swing.JTextField seedField;
    private javax.swing.JMenuItem setSeedButton;
    private javax.swing.JMenuItem showNavigatorButton;
    private javax.swing.JList<String> tileRestrictionList;
    private javax.swing.JMenu worldMenu;
    // End of variables declaration//GEN-END:variables
}
